# -*- coding: utf-8 -*-
"""eight.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EHZzBr3H0-jNY7IAVclYT5eafaz7g-Vj
"""

!pip install -U pip setuptools wheel
!pip install -U spacy
!python -m spacy download en_core_web_sm

import spacy
from spacy import displacy

# Load the language model
nlp = spacy.load("en_core_web_sm")
sentence = 'Deemed universities charge huge fees'

# nlp function returns an object with individual token information, 
# linguistic features and relationships
doc = nlp(sentence)

print ("{:<15} | {:<8} | {:<15} | {:<20}".format('Token','Relation','Head', 'Children'))
print ("-" * 70)

for token in doc:
  # Print the token, dependency nature, head and all dependents of the token
  print ("{:<15} | {:<8} | {:<15} | {:<20}"
         .format(str(token.text), str(token.dep_), str(token.head.text), str([child for child in token.children])))