# -*- coding: utf-8 -*-
"""four.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_TUR_tZrghUbMQy9CLWHj2X4kXFy29mc
"""

import re
import pandas as pd
from numpy import array

def read_text(filename):
        # open the file
        file = open(filename, mode='rt', encoding='utf-8')
        
        # read all text
        text = file.read()
        file.close()
        return text
      
def to_lines(text):
      sents = text.strip().split('\n')
      sents = [i.split('\t') for i in sents]
      return sents
  
#We can now use these functions to read the text into an array in our desired format.

data = read_text("deu.txt")
deu_eng = to_lines(data)
#deu_eng = array(deu_eng)

print(data[0:175])